name: cab_driver
description: Pick N Tow - Drive.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.1
  autoussdflutter: ^4.2.0
  awesome_notifications: ^0.7.4+1
  cloud_firestore: ^4.1.0
  connectivity_plus: ^3.0.2
  connectivity_plus_web: ^1.2.5
  cupertino_icons: ^1.0.2
  dropdown_textfield: ^1.0.8
  firebase_auth: ^4.1.2
  firebase_core: ^2.2.0
  firebase_database: ^10.0.1
  firebase_messaging: ^14.1.0
  firebase_storage: ^11.0.6
  flutter:
    sdk: flutter
  flutter_geofire: ^2.0.1
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.0
  flutter_termii: ^0.2.1
  fluttercontactpicker: ^4.7.0
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^10.2.1
  geolocator: ^9.0.2
  google_maps_flutter: ^2.0.8
  http: ^0.13.3
  image_picker: ^0.8.6
  just_audio: ^0.9.13
  lottie: ^2.0.0
  maps_toolkit: ^2.0.0
  mobile_number: ^2.1.1
  outline_material_icons: ^0.1.1
  permission_handler: ^10.2.0
  provider: ^6.0.0
  shared_preferences: ^2.0.18
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/
    - images/waiting.png
    - images/86682-car-loader.json
    - images/page.json
    - sounds/

  fonts:
    - family: Brand-Bold
      fonts:
        - asset: fonts/bolt-semibold.ttf

    - family: Brand-Regular
      fonts:
        - asset: fonts/bolt-regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
